# 苦力怕论坛 自动签到
# GitHub: https://github.com/xyz8848/KLPBBS_auto_sign_in

name: 'KLPBBS Auto Sign in'

on:
  schedule:
    - cron: '1 16 * * *' # 签到时间（注意时差！）
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Sign in
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DEBUG: ${{ secrets.DEBUG }}
          MAIL_ENABLE: ${{ secrets.MAIL_ENABLE }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          SERVERCHAN_ENABLE: ${{ secrets.SERVERCHAN_ENABLE }}
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: python main.py

      - uses: gautamkrishnar/keepalive-workflow@v1
